export interface Country {
  code: string
  name: string
  states?: { code: string; name: string }[]
}

export const COUNTRIES: Country[] = [
  {
    code: 'RS',
    name: 'Serbia',
    states: [
      { code: 'BG', name: 'Belgrade' },
      { code: 'NS', name: 'Novi Sad' },
      { code: 'NI', name: 'Niš' },
      { code: 'KG', name: 'Kragujevac' },
      { code: 'SU', name: 'Subotica' },
      { code: 'ZA', name: 'Zaječar' },
      { code: 'BO', name: 'Bor' },
      { code: 'VR', name: 'Vranje' },
      { code: 'KR', name: 'Kraljevo' },
      { code: 'SM', name: 'Smederevo' },
    ],
  },
  {
    code: 'HU',
    name: 'Hungary',
    states: [
      { code: 'BU', name: 'Budapest' },
      { code: 'PE', name: 'Pest' },
      { code: 'GY', name: 'Győr-Moson-Sopron' },
      { code: 'FE', name: 'Fejér' },
      { code: 'BA', name: 'Baranya' },
      { code: 'BO', name: 'Borsod-Abaúj-Zemplén' },
      { code: 'CS', name: 'Csongrád-Csanád' },
      { code: 'HB', name: 'Hajdú-Bihar' },
      { code: 'SZ', name: 'Szabolcs-Szatmár-Bereg' },
      { code: 'VE', name: 'Veszprém' },
      { code: 'ZA', name: 'Zala' },
    ],
  },
  {
    code: 'RU',
    name: 'Russia',
    states: [
      { code: 'MOW', name: 'Moscow' },
      { code: 'SPE', name: 'Saint Petersburg' },
      { code: 'SVE', name: 'Sverdlovsk Oblast' },
      { code: 'TA', name: 'Tatarstan' },
      { code: 'KDA', name: 'Krasnodar Krai' },
      { code: 'ROS', name: 'Rostov Oblast' },
      { code: 'SAM', name: 'Samara Oblast' },
      { code: 'NVS', name: 'Novosibirsk Oblast' },
      { code: 'BA', name: 'Bashkortostan' },
      { code: 'CHE', name: 'Chelyabinsk Oblast' },
    ],
  },
  {
    code: 'US',
    name: 'United States',
    states: [
      { code: 'AL', name: 'Alabama' },
      { code: 'AK', name: 'Alaska' },
      { code: 'AZ', name: 'Arizona' },
      { code: 'AR', name: 'Arkansas' },
      { code: 'CA', name: 'California' },
      { code: 'CO', name: 'Colorado' },
      { code: 'CT', name: 'Connecticut' },
      { code: 'DE', name: 'Delaware' },
      { code: 'FL', name: 'Florida' },
      { code: 'GA', name: 'Georgia' },
      { code: 'HI', name: 'Hawaii' },
      { code: 'ID', name: 'Idaho' },
      { code: 'IL', name: 'Illinois' },
      { code: 'IN', name: 'Indiana' },
      { code: 'IA', name: 'Iowa' },
      { code: 'KS', name: 'Kansas' },
      { code: 'KY', name: 'Kentucky' },
      { code: 'LA', name: 'Louisiana' },
      { code: 'ME', name: 'Maine' },
      { code: 'MD', name: 'Maryland' },
      { code: 'MA', name: 'Massachusetts' },
      { code: 'MI', name: 'Michigan' },
      { code: 'MN', name: 'Minnesota' },
      { code: 'MS', name: 'Mississippi' },
      { code: 'MO', name: 'Missouri' },
      { code: 'MT', name: 'Montana' },
      { code: 'NE', name: 'Nebraska' },
      { code: 'NV', name: 'Nevada' },
      { code: 'NH', name: 'New Hampshire' },
      { code: 'NJ', name: 'New Jersey' },
      { code: 'NM', name: 'New Mexico' },
      { code: 'NY', name: 'New York' },
      { code: 'NC', name: 'North Carolina' },
      { code: 'ND', name: 'North Dakota' },
      { code: 'OH', name: 'Ohio' },
      { code: 'OK', name: 'Oklahoma' },
      { code: 'OR', name: 'Oregon' },
      { code: 'PA', name: 'Pennsylvania' },
      { code: 'RI', name: 'Rhode Island' },
      { code: 'SC', name: 'South Carolina' },
      { code: 'SD', name: 'South Dakota' },
      { code: 'TN', name: 'Tennessee' },
      { code: 'TX', name: 'Texas' },
      { code: 'UT', name: 'Utah' },
      { code: 'VT', name: 'Vermont' },
      { code: 'VA', name: 'Virginia' },
      { code: 'WA', name: 'Washington' },
      { code: 'WV', name: 'West Virginia' },
      { code: 'WI', name: 'Wisconsin' },
      { code: 'WY', name: 'Wyoming' },
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    states: [
      { code: 'AB', name: 'Alberta' },
      { code: 'BC', name: 'British Columbia' },
      { code: 'MB', name: 'Manitoba' },
      { code: 'NB', name: 'New Brunswick' },
      { code: 'NL', name: 'Newfoundland and Labrador' },
      { code: 'NS', name: 'Nova Scotia' },
      { code: 'ON', name: 'Ontario' },
      { code: 'PE', name: 'Prince Edward Island' },
      { code: 'QC', name: 'Quebec' },
      { code: 'SK', name: 'Saskatchewan' },
    ],
  },
  { code: 'DE', name: 'Germany' },
  { code: 'FR', name: 'France' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'BE', name: 'Belgium' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AT', name: 'Austria' },
  { code: 'PL', name: 'Poland' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'RO', name: 'Romania' },
  { code: 'HR', name: 'Croatia' },
  { code: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'GR', name: 'Greece' },
  { code: 'PT', name: 'Portugal' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'DK', name: 'Denmark' },
  { code: 'FI', name: 'Finland' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'JP', name: 'Japan' },
  { code: 'CN', name: 'China' },
  { code: 'IN', name: 'India' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'TR', name: 'Turkey' },
  { code: 'UA', name: 'Ukraine' },
]
